### PR TITLE
For #8: Fixed issue with SwipeRefreshLayout

### LINKED ISSUE #8: issue when using with SwipeRefreshLayout
it doesn't work properly with SwipeRefreshLayout.
here is code I have modified in your sample app

```
<androidx.swiperefreshlayout.widget.SwipeRefreshLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/swipeRefreshLayout"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <com.qtalk.recyclerviewfastscroller.RecyclerViewFastScroller
        android:id="@+id/fast_scroller"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:handleHeight="32dp"
        app:handleWidth="@dimen/default_handle_size">

        <androidx.recyclerview.widget.RecyclerView
            android:id="@+id/basic_recycler_view"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:layout_marginLeft="@dimen/recycler_view_margin"
            android:layout_marginRight="@dimen/recycler_view_margin" />
    </com.qtalk.recyclerviewfastscroller.RecyclerViewFastScroller>
</androidx.swiperefreshlayout.widget.SwipeRefreshLayout>
```

here is the issue what I am facing

### PR DESCRIPTION
**Pull request by naveenchandan**
Fixed Fast scroller issue where the thumb is not scrollable when parent is SwipeRefreshLayout, so added custom attribute "supportSwipeToRefresh" to enable support for fast scrolling when parent layout is SwipeRefreshLayout.

Fixes #8

### CODE REVIEW

**Comment by shahsurajk** [comment]
Always mention the issue that you fixing with fixes #8 . This will automatically fix the issue when the PR is merged.

File: recyclerviewfastscroller/src/main/java/com/qtalk/recyclerviewfastscroller/RecyclerViewFastScroller.kt [hunk 1]
```diff
@@ -214,6 +218,9 @@ class RecyclerViewFastScroller @JvmOverloads constructor(
 
             trackView.background = attribs.getDrawable(R.styleable.RecyclerViewFastScroller_trackDrawable)
 
+            if (it.getBoolean(R.styleable.RecyclerViewFastScroller_supportSwipeToRefresh,false))
```
Comment (shahsurajk) [inline recyclerviewfastscroller/src/main/java/com/qtalk/recyclerviewfastscroller/RecyclerViewFastScroller.kt]: it's a good practice to have curly braces surrounding an `if` condition. Could you refactor this to change it?

**Review by shahsurajk — CHANGES_REQUESTED** [review]
Looks good overall, just a couple of nits.

File: recyclerviewfastscroller/src/main/java/com/qtalk/recyclerviewfastscroller/RecyclerViewFastScroller.kt (hunk 1 above)
Comment (naveenchandan) [reply recyclerviewfastscroller/src/main/java/com/qtalk/recyclerviewfastscroller/RecyclerViewFastScroller.kt]: ok, I will do that
